### ISSUE TITLE
v1.0.0

### ISSUE THREAD

**Issue by faessler** [faessler/react-media-components#1]
Get our first official version published. See also [roadmap](https://github.com/faessler/react-media-components/wiki/Roadmap#v100) for more information about future features.

## Implementation preview
**Config file:**
```json
{
  "image": {
    "sizes": {
      "0": "414",
      "414": "768",
      "768": "1024",
      "1024": "1200",
      "1200": "1920"
    },
    "formats": ["AVIF", "WebP"],
    "quality": 70,
    "deviceSizes": [375, 768, 1024, 1200], // canceled in favour of sizes
    "maxSize": 1920, // canceled in favour of sizes
  },
  "video": {}, // future stuff
  "audio": {}, // future stuff
}
```

**Component usage:**
```jsx
import { Image } from "react-media-components";

<Image src="/path/to/image.png" />
```

## Tasks
- [x] Create proper README.md
- [x] Implement solution for automatic changelog generation (see [lob/generate-changelog](https://github.com/lob/generate-changelog))
- [ ] Add CI to automatically publish package to npm registry on git tag push
- [ ] Create react Image component
